export const AGENT_CREATED="AGENT_CREATED";
export const AGENT_DELETED="AGENT_DELETED";
export const AGENTS_RETRIEVED="AGENTS_RETRIEVED";
export const AGENT_RETRIEVED="AGENT_RETRIEVED";
export const AGENT_UPDATED="AGENT_UPDATED";