
export const PROPERTY_CREATED = "PROPERTY_CREATED";
export const PROPERTIES_RETRIEVED = "PROPERTIES_RETRIEVED";
export const PROPERTY_RETRIEVED = "PROPERTY_RETRIEVED";
export const PROPERTY_UPDATED = "PROPERTY_UPDATED";
export const PROPERTY_DELETED = "PROPERTY_DELETED";